server:
  port: 8761
eureka:
  instance:
    hostname: peer1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer2:8769/eureka/
  server:
    enableSelfPreservation: true
    renewalPercentThreshold: 0.49
spring:
  profiles: peer1
  application:
    name: eurka-server