server:
  port: 9001
spring:
  application:
    name: service-feign
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
feign:
  hystrix:
    enabled: true